film/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField,SelectField,FileField,TextAreaField,IntegerField

"""
登录表单:
1. 账号
2. 密码
3. 登录按钮
"""
from wtforms.validators import DataRequired, EqualTo, ValidationError
from film.models2 import User
class LoginForm(FlaskForm):
    account = StringField(
        label=u"账号",
        validators=[DataRequired(u"账号不能为空")],
        description=u"账号",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入账号!"
        }
    )
    pwd = PasswordField(
        label=u"密码",
        validators=[DataRequired(u"密码不能为空")],
        description=u"密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入密码!"
        }
    )
    submit = SubmitField(
        u"登录",
        render_kw={
            "class": "btn btn-primary"
        }
    )
    '''def validate_account(self, field):
        account = field.data
        user = User.query.filter_by(account=account).first()
        print(user)
        if not user:
            raise ValidationError(u"账号不存在")'''
    def validate_pwd(self, field):
        pwd = field.data
        #print(self.account)
        account = self.account.data
        user = User.query.filter_by(account=account).first()
        #print(user)
        if not user:
            raise ValidationError(u"账号或密码错误")
        user = User.query.filter_by(account=self.account.data).first()
        if not user.check_pwd(pwd):
            raise ValidationError(u"账号或密码错误")


from wtforms.validators import DataRequired, EqualTo, ValidationError
from film.models2 import User

class RegisterForm(FlaskForm):
    account = StringField(
        validators=[DataRequired(u"账号不能为空")],
        description=u"账号",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入账号"
        }
    )
    pwd = PasswordField(
        validators=[DataRequired(u"密码不能为空")],
        description=u"密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入密码"
        }
    )
    re_pwd = PasswordField(
        validators=[DataRequired(u"密码不能为空"),EqualTo('pwd',message=u'两次密码不一致')],
        description=u"确认密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请确认密码"
        }
    )

    captcha = StringField(
        validators=[],
        description=u"验证码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入验证码"
        }
    )
    submit = SubmitField(
        u"注册",
        render_kw={
            "class": "btn btn-primary"
        }
    )

    def validate_account(self, field):
        account = field.data
        user = User.query.filter_by(account=account).count()
        if user > 0:
            raise ValidationError(u"账号已存在")

    def validate_captcha(self, field):
        captcha = field.data
        from flask import session
        if not session["captcha"]:
            raise ValidationError(u"非法操作")
        if session["captcha"].lower() != captcha.lower():
            raise ValidationError(u"验证码不正确")
    '''原验证码校验，不清楚form_session的导包，替换为flask的导包session
        def validate_captcha(self, field):
            captcha = field.data
            if not form_session["captcha"]:
                raise ValidationError(u"非法操作")
            if form_session["captcha"].lower() != captcha.lower():
                raise ValidationError(u"验证码不正确")
    '''
class ArticleAddForm(FlaskForm):
    title = StringField(
        validators=[
            DataRequired(u"内容不能为空")
        ],
        description=u"标题",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入标题"
        }
    )
    # 强制类型为整型
    category = SelectField(
        validators=[
            DataRequired(u"分类不能为空")
        ],
        description=u"分类",
        choices=[(1, u"科技"), (2, u"搞笑"), (3, u"军事")],
        default=3,
        coerce=int,
        render_kw={
            "class": "form-control"
        }
    )
    logo = FileField(
        validators=[],
        description=u"封面",
        render_kw={
            "class": "form-control-file",
        }
    )
    content = TextAreaField(
        validators=[
            DataRequired(u"内容不能为空")
        ],
        description=u"内容",
        render_kw={
            "style": "height:300px;",
            "id": "content"
        }
    )
    submit = SubmitField(
        u"发布文章",
        render_kw={
            "class": "btn btn-primary"
        }
    )

class ArticleEditForm(FlaskForm):
    id = IntegerField(
        validators=[
            DataRequired(u"内容不能为空")
        ],

    )
    title = StringField(
        validators=[
            DataRequired(u"内容不能为空")
        ],
        description=u"标题",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入标题"
        }
    )
    # 强制类型为整型
    category = SelectField(
        validators=[
            DataRequired(u"分类不能为空")
        ],
        description=u"分类",
        choices=[(1, u"科技"), (2, u"搞笑"), (3, u"军事")],
        default=3,
        coerce=int,
        render_kw={
            "class": "form-control"
        }
    )
    logo = FileField(
        validators=[],
        description=u"封面",
        render_kw={
            "class": "form-control-file",
        }
    )
    content = TextAreaField(
        validators=[
            DataRequired(u"内容不能为空")
        ],
        description=u"内容",
        render_kw={
            "style": "height:300px;",
            "id": "content"
        }
    )
    submit = SubmitField(
        u"发布文章",
        render_kw={
            "class": "btn btn-primary"
        }
    )

film/__init__.py
from flask import Flask
#import pymysql
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import MetaData

convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

metadata = MetaData(naming_convention=convention)

db = SQLAlchemy(metadata=metadata)
from .models import *
from .models2 import *

def create_app():
    app = Flask(__name__)
    app.debug = True

    #app.config['SQLALCHEMY_DATABASE_URI'] = "mysql+mysqlconnector://root:chis1chang@127.0.0.1:3306/movie?charset=utf8"
    app.config['SQLALCHEMY_DATABASE_URI'] = "mysql+pymysql://root:chis1chang@127.0.0.1:3306/movie?charset=utf8"
    app.config['SQLALCHEMY_BINDS'] = {
        'artcms': 'mysql+pymysql://root:chis1chang@127.0.0.1:3306/artcms?charset=utf8',
        #'movie':"mysql+pymysql://root:chis1chang@127.0.0.1:3306/movie?charset=utf8",
    }
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    app.config['SQLALCHEMY_POOL_SIZE'] = 10
    app.config['SQLALCHEMY_MAX_OVERFLOW'] = 5
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    app.config['SQLALCHEMY_COMMIT_TEARDOWN'] = True

    from film.home import home as home_blueprint
    from film.admin import admin as admin_blueprint
    app.register_blueprint(home_blueprint)
    app.register_blueprint(admin_blueprint,url_prefix='/admin')
    db.init_app(app)

    app.config["SECRET_KEY"] = "12345678"
    import os
    app.config["uploads"] = os.path.join(os.path.dirname(__file__), "static","uploads")

    return app

film/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin',__name__)
import film.admin.views

film/admin/views.py
from . import admin

@admin.route("/")
def index():
    return "<h1 style='color:red'>this is admin</h1>"

film/home/__init__.py
from flask import Blueprint
 
home = Blueprint('home',__name__)

import film.home.views

film/home/views.py
from . import home
from flask import render_template,redirect,url_for,request

@home.route("/")
def index():
    return "<h1 style='color:red'>this is home</h1>"
from functools import wraps
def user_login_req(f):
    @wraps(f)
    def login_req(*args,**kwargs):
        if "user" not in session:
            return redirect(url_for('home.login', next=request.url ))
        return f(*args,**kwargs)
    return login_req


from .forms import LoginForm
@home.route("/login/",methods=["GET","POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        data = form.data
        session["user"] = data["account"]
        flash("登录成功", "ok")
        return redirect("/art/list/1/")
    return render_template('login.html',title='登录',form=form)

@home.route("/logout/",methods=["GET"])
@user_login_req
def logout():
    session.pop("user", None)
    return redirect("/login/",)



from .forms import RegisterForm
from film.models2 import User
from werkzeug.security import generate_password_hash
from datetime import datetime
from film import db
from flask import flash
@home.route("/register/",methods=["GET","POST"])
def register():
    #print('你好')
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        print(data)
        user = User(
            account=data["account"],
            # 对于pwd进行加密
            pwd=generate_password_hash(data["pwd"]),
            add_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )
        db.session.add(user)
        db.session.commit()
        flash("注册成功！","ok")
        return redirect('/art/list/')

    return render_template("register.html", title="注册", form=form,session=session)



from .forms import ArticleAddForm
from werkzeug.utils import secure_filename

from film.models2 import Article
@home.route("/art/add/",methods=["GET","POST"])
@user_login_req
def art_add():
    form = ArticleAddForm()
    if form.validate_on_submit():
        data = form.data
        #print('aaa',data)
        from flask import current_app
        # print(current_app.static_folder)
        file = secure_filename(form.logo.data.filename)
        logo = change_name(file)
        #print('logo type',type(logo),logo)
        if not os.path.exists(current_app.config["uploads"]):
            os.makedirs(current_app.config["uploads"])
        #print('pahtht:::::',type(current_app.config["uploads"]))
        # 保存文件
        pa = os.path.join(current_app.config["uploads"], logo)
        print('pahtht:::::',pa)
        form.logo.data.save(pa)
        # 获取用户ID
        user = User.query.filter_by(account=session["user"]).first()
        user_id = user.id
        # 保存数据，Article
        article = Article(
            title=data["title"],
            category=data["category"],
            user_id=user_id,
            logo=logo,
            content=data["content"],
            add_time=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )
        db.session.add(article)
        db.session.commit()
        flash(u"发布文章成功", "ok")
    return render_template("art_add.html",title="发布文章",form=form)
from .forms import ArticleEditForm
@home.route("/art/edit/<int:id>/",methods=["GET","POST"])
@user_login_req
def art_edit(id):
    form = ArticleEditForm()
    article = Article.query.get_or_404(int(id))
    #print(article.id)
    if request.method == "GET":
        form.content.data = article.content
        form.category.data = article.category
        # 莫名其妙赋初值:不赋初值表单提交时会提示封面为空
        # 放在这里修复显示请选择封面的错误
    #form.logo.data = article.logo
    #print('data>>>>>',form.data,'logo>>>',)
    if form.validate_on_submit():
        data = form.data
        # 上传logo
        print('sss',form.logo.data,type(form.logo.data))
        if form.logo.data:

            file = secure_filename(form.logo.data.filename)
            #print('llll')
            logo = change_name(file)

            from flask import current_app
            if not os.path.exists(current_app.config["uploads"]):
                os.makedirs(current_app.config["uploads"])

            # 保存文件
            pa = os.path.join(current_app.config["uploads"], logo)
            #print('pahtht:::::', pa)
            form.logo.data.save(pa)
            article.logo = logo

        article.title = data['title']
        article.content = data['content']
        article.category = data['category']
        db.session.add(article)
        db.session.commit()
        flash(u"编辑文章成功", "ok")
        return redirect('art/list/1')
    return render_template("art_edit.html", form=form, title="编辑文章", article=article)

@home.route("/art/list/<int:page>/",methods=["GET"])
def art_list(page):
    if page is None:
        page = 1
        # 只展示当前用户才能看到的内容
    user = User.query.filter_by(account=session["user"]).first()
    user_id = user.id
    page_data = Article.query.filter_by(
        user_id=user_id
    ).order_by(
        Article.add_time.desc()
    ).paginate(page=page, per_page=1)

    category = [(1, u"科技"), (2, u"搞笑"), (3, u"军事")]
    return render_template("art_list.html", title="文章列表", page_data=page_data, category=category)
    #return render_template("art_list.html", title="文章列表", page_data=page_data)


@home.route("/art/del/<int:id>",methods=["GET"])
@user_login_req
def art_del(id):
    article = Article.query.get_or_404(int(id))
    db.session.delete(article)
    db.session.commit()
    flash("删除《%s》成功!" % article.title, "ok")
    return redirect("/art/list/1")


# 验证码
from flask import session, Response
@home.route("/captcha/", methods=["GET"])
def captcha():
    from film.util.catpcha  import Captcha
    import os
    c = Captcha()
    info = c.create_captcha()
    '''
    原设计catpcha()生成验证码并保存成jpeg格式文件，现在修改为该函数传递过来二进制图片流
    image = os.path.join('film/util/', "static/captcha") + "/" + info["image_name"]
    with open(image, 'rb') as f:
        image = f.read()
    return Response(image, mimetype="jpeg")
    '''
    session['captcha'] = info["captcha"]
    return Response(info['image_2'])


from werkzeug.utils import secure_filename
import os ,uuid
# 设置上传封面图路径
# 修改文件名称
def change_name(name):
    info = os.path.splitext(name)
    # 文件名: 时间格式字符串+唯一字符串+后缀名
    name = datetime.now().strftime("%Y%m%d%H%M%S")+str(uuid.uuid4().hex)+info[-1]
    return name
import json,re

@home.route('/upload/', methods=['GET', 'POST'])
def upload():
    from flask import current_app
    #print(current_app.static_folder)
    action = request.args.get('action')
    with open(os.path.join(current_app.static_folder, 'ue', 'php','config.json')) as fp:
        try:
            # 删除 `/**/` 之间的注释
            CONFIG = json.loads(re.sub(r'\/\*.*\*\/', '', fp.read()))
        except:
            CONFIG = {}

    if action == 'config':
        # 初始化时，返回配置文件给客户端
        result = CONFIG

    return json.dumps(result)

film/templates/art_add.html
{% extends 'art_base.html' %}
{% block content %}
<div class="col-md-9">
                <div class="card">
                     <div class="card-header">{{ title }}</div>
                     <div class="card-body">
<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label>标题</label>
       {{ form.title }}
         {%   for error in form.title.errors %}
                        <p style="color:red">{{ error }}  </p>
                        {%   endfor %}
    </div>
    <div class="form-group">
        <label>分类</label>
        {{ form.category }}
         {%   for error in form.category.errors %}
                        <p style="color:red">{{ error }}  </p>
                        {%   endfor %}
    </div>
    <div class="form-group">
        <label>封面</label>
         {{ form.logo }}
        {%   for error in form.logo.errors %}
                        <p style="color:red">{{ error }}  </p>
                        {%   endfor %}
        <img data-src="holder.js/300x160" style="margin-top: 6px;">
        <a class="btn btn-primary" style="margin-top: 6px;">上传封面</a>
    </div>
    <div class="form-group">
         <label>内容</label>
         {{ form.content }}
        {%   for error in form.content.errors %}<p style="color:red">{{ error }}  </p>
            {%   endfor %}
    </div>

{{ form.csrf_token }}
     {{ form.submit }}
</form>
                     </div>
                </div>

    </div>



{% endblock %}

{% block css %}
<script src="{{ url_for('static',filename='ue/ueditor.config.js') }}"></script>
<script src="{{ url_for('static',filename='ue/ueditor.all.js') }}"></script>
<script src="{{ url_for('static',filename='ue/lang/zh-cn/zh-cn.js') }}"></script>

{% endblock %}

{% block sc %}
var ue = UE.getEditor("content", {
        serverUrl: "/upload/"
    });
{% endblock %}

film/templates/art_base.html
<!doctype html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>文章管理系统</title>
   <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/bootstrap.css') }}">

{% block css %} {% endblock %}

</head>
<body>

<nav class="navbar navbar-light" style="background-color: #062c33">
    <div class="container">
        <a class="navbar-brand" style="color: #ffffff"> 文章管理系统</a>

        {% if session['user'] %}

        <a class="btn navbar-brand pull-right" href="/logout/">{{ session['user'] }} -> 退出</a>
        {% else %}
            <a class="btn navbar-brand pull-right" href="/login/">登录 </a>
        {% endif %}
    </div>
</nav>

<div class="container" style="margin-top: 6px">
    <div class="row">
        <div class="col-md-3">
            {% include 'art_menus.html' %}
        </div>

        {% block content %}

        {% endblock %}
    </div>



</div>
<script src="{{ url_for('static',filename='js/jquery-3.3.1.slim.min.js') }}"></script>

<script src="{{ url_for('static',filename='js/bootstrap.js') }}"></script>
<script src="{{ url_for('static',filename='js/popper.min.js') }}"></script>
<script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>


<script>
    $(document).ready(function () {
        $("#m2").addClass("active");
    });

     {% block sc %}

{% endblock %}
</script>

</body>
</html>

film/templates/art_edit.html
{% extends 'art_base.html' %}
{% block content %}
        <div class="col-md-9">
                <div class="card">
                <div class="card-header">文章列表</div>
                 <div class="card-body">
                     <form method="post" enctype="multipart/form-data">
                     <table class="table table-bordered">

                             标题
                             <input type="hidden" name="id" value="{{ article.id }}">



                         {{ form.title(value=article.title)  }}
                         {{ form.logo }}
<img src="/static/uploads/{{ article.logo }}" style="margin-top:6px;width:300px;height:180px">
                         {{   form.content(value=article.content) }}
                        {{ form.csrf_token }}
                            {{ form.submit }}

                     </form>
                 </div>
            </div>


        </div>
    </div>
{% endblock %}


{% block css %}
<script src="{{ url_for('static',filename='ue/ueditor.config.js') }}"></script>
<script src="{{ url_for('static',filename='ue/ueditor.all.js') }}"></script>
<script src="{{ url_for('static',filename='ue/lang/zh-cn/zh-cn.js') }}"></script>

{% endblock %}

{% block sc %}
var ue = UE.getEditor("content", {
        serverUrl: "/upload/"
    });
{% endblock %}

film/templates/art_list.html
{% extends 'art_base.html' %}
{% import 'page.html'as pg %}
{% block content %}
    {% for msg in get_flashed_messages(category_filter=['ok']) %}
    <p style="color:green">{{ msg }}</p>
    {% endfor %}
<div class="col-md-9">
                <div class="card">
                     <div class="card-header">{{ title }}</div>
                     <div class="card-body">

                         <table class="table table-bordered">
                         <thead>
                         <tr>
                             <th>标题</th>
                             <th>分类</th>
                             <th>封面</th>
                             <th>作者</th>
                             <th>发布时间</th>
                             <th>管理操作</th>
                         </tr>
                         </thead>
                          <tbody>
                          {% for v in page_data.items %}
                         <tr>
                             <td> {{ v.title }}</td>
                             <td>{{ category[v.category-1][1]}}</td>
                             <td> <img src='/static/uploads/{{ v.logo }}' style="width:75px;height:40px" ></td>
                             <td>{{ session['user'] }}</td>
                                <td>{{ v.add_time }}</td>
                          <td>
                             <a class="btn btn-sm btn-outline-success" href="{{ url_for('home.art_edit',id=v.id) }}">编辑</a>
                             <a class="btn btn-sm btn-outline-danger" href="{{ url_for('home.art_del',id=v.id) }}">删除</a>
                         </td>
                         </tr>
                         {% endfor %}
                          </tbody>

                      </table>
{{ pg.page(page_data,'home.art_list') }}

                     </div>
                </div>

    </div>
{% endblock %}

film/templates/art_menus.html
<div class="list-group">
                <a href="/art/add/" class="list-group-item list-group-item-action">发布文章</a>
                <a href="/art/list/1/" class="list-group-item list-group-item-action">文章列表</a>
            </div>

film/templates/login.html
{% extends "user_base.html" %}
{% block content %}
                    <form method="post">
                        <div class="form-group">
                            <label>账号</label>
                            {{ form.account }}
                            {% for error in form.account.errors %}
                            <p style="color:red">{{ error }}</p>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label>密码</label>
                            {{ form.pwd }}
                            {% for error in form.pwd.errors %}
                            <p style="color:red">{{ error }}</p>
                            {% endfor %}
                        </div>
                    <a href="/register/">注册</a><br><br>
                        {{ form.csrf_token }}
                        {{ form.submit }}
                    </form>
{% endblock %}

film/templates/page.html
{% macro page(data,url) %}
    {% if data %}
            <nav>
                <ul class="pagination">
                    {% if data.has_prev %}
                        <li class="page-item"><a class="page-link" href="{{ url_for(url,page=data.prev_num) }}">上一页</a></li>
                    {% endif %}
                    {% for v in data.iter_pages() %}
                             {% if v !=data.page %}
                                     <li class="page-item"><a class="page-link" href="{{ url_for(url,page=v) }}">{{ v }}</a></li>
                             {% endif %}
                             {% if v == data.page %}
                                 <li class="page-item active"><a class="page-link" href="#">{{ v }}</a></li>
                             {% endif %}
                    {% endfor %}
                    {% if data.has_next %}
                        <li class="page-item"><a class="page-link" href="{{ url_for(url,page=data.next_num) }}">下一页</a></li>
                    {% endif %}
                </ul>
            </nav>
    {% endif %}
{% endmacro %}

film/templates/register.html
{% extends "user_base.html" %}
{% block content %}
                    <form method="post">

                    <div class="form-group">
                        <label>账号</label>
                        {{ form.account }}
                        {%   for error in form.account.errors %}
                        <p style="color:red">{{ error }}  </p>
                        {%   endfor %}
                    </div>
                    <div class="form-group">
                        <label>密码</label>
                        {{ form.pwd }}
                        {%   for error in form.pwd.errors %}
                        <p style="color:red">{{ error }}  </p>
                        {%   endfor %}
                    </div>
                    <div class="form-group">
                        <label>确认密码</label>
                        {{ form.re_pwd }}
                        {%   for error in form.re_pwd.errors %}
                        <p style="color:red">{{ error }}  </p>
                        {%   endfor %}
                    </div>
                    <div class="form-group">
                        <label>验证码</label>
                        {{ form.captcha }}
                        {%   for error in form.captcha.errors %}
                        <p style="color:red">{{ error }}  </p>
                        {%   endfor %}
                    <!-- 初始占位<img data-src="holder.js/180x50" style="margin-top: 6px">-->
                  <!--   验证码显示，但必须刷新网页       <img src="/captcha/" style="width:180px;height:50px"> -->
                    <img  title="点击切换" src="/captcha/" onclick="this.src='/captcha/?'+Math.random()" style="width: 180px; height: 50px;margin-top: 6px;">

                    </div>
                    <a href="/login/">已有账号!前往登录</a>
                    <br><br>
                     {{ form.csrf_token }}
                    {{ form.submit }}

                    </form>
{% endblock %}

film/templates/user_base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/bootstrap.css') }}">
    <meta charset="UTF-8">
    <title>{{ title }}页面</title>
</head>
<body>



<script src="{{ url_for('static',filename='js/jquery-3.3.1.slim.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/popper.min.js') }}"></script>
<script src="{{ url_for('static',filename='js/bootstrap.js') }}"></script>

<div class="container" style="margin-top: 100px">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-center">文章管理系统</h3>
        </div>


        <div class="col-md-6 col-md-offset-3">
                <div class="card-header">{{ title }}</div>
                <div class="card-body">
{% block content %}

{% endblock %}




                </div>
        </div>
    </div>
</div>

<script src="https://cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
{% block js %}

{% endblock %}

</body>
</html>